services:
  life_db:
    image: postgres:16-alpine
    ports:
      - "10531:5432"
    volumes:
      - life_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "postgres"
volumes:
  life_db: