source 'https://rubygems.org'

gem 'bootsnap', require: false
gem 'jbuilder'
gem 'pg'
gem 'puma', '>= 5.0'
gem 'rack-cors'
gem 'rails', '~> 7.2.2', '>= 7.2.2.1'
gem 'tzinfo-data', platforms: %i[windows jruby]

group :development, :test do
  gem 'brakeman', require: false
  gem 'debug', platforms: %i[mri windows], require: 'debug/prelude'
  gem 'dotenv-rails'
  gem 'factory_bot_rails'
  gem 'rspec-rails'
  gem 'rubocop-rails-omakase', require: false
end

group :development do
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  gem 'ruby-lsp'
end

group :test do
  gem 'rspec-request_describer'
  gem 'faker'
end
